# Generated by Django 3.1.5 on 2021-02-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_auto_20210211_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='Резюме по умолчанию', max_length=50),
        ),
    ]
