# Generated by Django 3.1.5 on 2021-02-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_auto_20210211_0650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['title'], 'verbose_name': 'Квалификация', 'verbose_name_plural': 'Квалификации'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['title'], 'verbose_name': 'Статус соискателя', 'verbose_name_plural': 'Статусы соискателя'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['title'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='application',
            name='written_username',
            field=models.CharField(max_length=50),
        ),
    ]
