# Generated by Django 3.1.5 on 2021-02-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_auto_20210211_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='portfolio',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
