# Generated by Django 3.1.5 on 2021-02-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0014_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grade',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
