# Generated by Django 3.1.5 on 2021-02-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0015_auto_20210214_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Регион, город'),
        ),
    ]
